### ISSUE TITLE
Heroku problem

### ISSUE THREAD

**Issue by Visi78** [sillygwailo/goodreads-random#1]
The send to Heroku function does not work. It says the app does not exist.

**Comment by sillygwailo** [comment]
The Heroku build should work now. I just tested it, after changing the CALLBACK_URL environment variable to be optional. You will need to set it after the build happens, however, to `https://app-name-12345.herokuapp.com/auth/goodreads/callback` (replace `app-name-12345` with the name you or Heroku have given the app).

**Comment by sillygwailo** [comment]
I'm going to close this, since I haven't heard a response. Hopefully making the CALLBACK_URL optional to begin with, with the need to still set it once you deploy to Heroku, is the fix for this.
