### ISSUE TITLE
Heroku deployment but does nothing

### ISSUE THREAD

**Issue by ghost** [sillygwailo/goodreads-random#2]
I deployed mine from Heroku and put in my key and secret and changed the URL to include my app name, but after I deployed and viewed it, nothing happened. First I followed a link and gave it permission from Goodreads. Then it went back to the page on Heroku telling me to log in to my Goodreads to view it. No link worked to do anything but refresh the page aside from the Contact link. Didn't mess with any of the code.

**Comment by sillygwailo** [comment]
What do you mean by "nothing happened"? Did it redirect back to your app, not logged in? Or did it stop at Goodreads with a message that says `This app is already authorized.`? It will do that if the `CALLBACK_URL` variable is not set correctly. It should be set to something like this:

```
https://your-app-name.herokuapp.com/auth/goodreads/callback
```

**Comment by ghost** [comment]
Sorry it took me so long.
Originally it did nothing as in, the page is not responding.
Now it's saying "This app is already authorized." I took the callback_url you pasted above and substituted my app name and it just took me to my Goodreads home page with "This app is already authorized." Goodreads is functioning as normal, so I'm just not seeing where the random book is suggested. It's working perfectly normal and I tried going to different shelves to have it work on those, but it just functioned as Goodreads is supposed to function without the randomization.

**Comment by ghost** [comment]
Went back in and started the whole thing over from scratch and copied the CALLBACK_URL you mentioned, and it works perfectly as far as I can tell. Thanks again and sorry for the long wait.
